
CREATE TABLE IF NOT EXISTS PAUTA (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  theme VARCHAR(100) NOT NULL,
  session_started_time TIMESTAMP NULL,
  ends_in INT NULL,
  open_session BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS VOTO (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  associado_id INT NOT NULL,
  pauta_id INT NOT NULL,
  voto VARCHAR(4) NOT NULL
);